import type { Metadata } from "next";
// ALTERAÇÃO POSSÍVEL:
// ONDE: neste import
// CÓDIGO:
//   import type { Metadata, Viewport } from "next";
// RESULTADO:
//   permite definir viewport global (mobile-first)
// (não aplicado, apenas comentado)

import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Link from "next/link";
import Relogio from "@/app/components/Relogio";

// ALTERAÇÃO POSSÍVEL:
// ONDE: nos imports
// CÓDIGO:
//   remover Relogio
// RESULTADO:
//   layout passa a Server-only (Relogio é Client Component)
// (não aplicado, apenas comentado)







const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],

  // ALTERAÇÃO POSSÍVEL:
  // ONDE: nesta configuração
  // CÓDIGO:
  //   display: "swap"
  // RESULTADO:
  //   melhora performance e evita flash de fonte
  // (não aplicado, apenas comentado)
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  // ALTERAÇÃO POSSÍVEL:
  // ONDE: neste title
  // CÓDIGO:
  //   title: "DIW | React & Next.js"
  // RESULTADO:
  //   título mais descritivo no browser
  // (não aplicado, apenas comentado)

  description: "Generated by create next app",
  // ALTERAÇÃO POSSÍVEL:
  // ONDE: nesta description
  // CÓDIGO:
  //   description: "Projeto académico de DIW com Next.js"
  // RESULTADO:
  //   melhora SEO
  // (não aplicado, apenas comentado)
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;

  // ALTERAÇÃO POSSÍVEL:
  // ONDE: nesta tipagem
  // CÓDIGO:
  //   readonly children: React.ReactNode;
  // RESULTADO:
  //   garante que children não é alterado
  // (não aplicado, apenas comentado)
}>) {

  const data = new Date();
  // ALTERAÇÃO POSSÍVEL:
  // ONDE: nesta linha
  // CÓDIGO:
  //   const year = new Date().getFullYear();
  // RESULTADO:
  //   evita criar objeto Date completo
  // (não aplicado, apenas comentado)

  return (
    <html lang="en">
      {/* ALTERAÇÃO POSSÍVEL:
          ONDE: neste lang
          CÓDIGO:
            lang="pt"
          RESULTADO:
            acessibilidade e SEO em português
          (não aplicado, apenas comentado) */}

      <body
        className='flex flex-col justify-start gap-4 p-20 items-center min-h-screen'
        // ALTERAÇÃO POSSÍVEL:
        // ONDE: nesta className
        // CÓDIGO:
        //   className={`${geistSans.variable} ${geistMono.variable} ...`}
        // RESULTADO:
        //   aplica fontes globalmente
        // (não aplicado, apenas comentado)
      >

        <header className="flex flex-col items-center">
          {/* ALTERAÇÃO POSSÍVEL:
              ONDE: nesta tag <header>
              CÓDIGO:
                <header className="sticky top-0 bg-white z-50">
              RESULTADO:
                header fixo no topo
              (não aplicado, apenas comentado) */}

          <h1>
            React & Next.js
            {/* ALTERAÇÃO POSSÍVEL:
                ONDE: dentro do h1
                CÓDIGO:
                  <span>DIW</span>
                RESULTADO:
                  subtítulo no header
                (não aplicado, apenas comentado) */}
          </h1>

          <nav className="flex gap-4">
            {/* ALTERAÇÃO POSSÍVEL:
                ONDE: nesta nav
                CÓDIGO:
                  <nav aria-label="Navegação principal">
                RESULTADO:
                  melhora acessibilidade
                (não aplicado, apenas comentado) */}

            <Link href="/">Intro</Link>
            <Link href="/sobre">Sobre</Link>
            <Link href="/caracteristicas">Características</Link>
            <Link href="/tecnologias">Tecnologias</Link>
            <Link href="/projetos">Projetos</Link>
            <Link href="/contador">Contador</Link>
            <Link href="/input">Input</Link>
            <Link href="/produtos">Produtos</Link>

            {/* ALTERAÇÃO POSSÍVEL (ADIÇÃO):
                ONDE: aqui
                CÓDIGO:
                  <Link href="/contactos">Contactos</Link>
                RESULTADO:
                  adiciona nova rota
                (não aplicado, apenas comentado) */}
          </nav>
        </header>

        <main
          className="bg-blue-200 p-5 rounded-2xl max-w-2xl min-h-[70vh]"
          // ALTERAÇÃO POSSÍVEL:
          // ONDE: nesta className
          // CÓDIGO:
          //   max-w-4xl
          // RESULTADO:
          //   aumenta largura do conteúdo
          // (não aplicado, apenas comentado)
        >
          {children}
          {/* ALTERAÇÃO POSSÍVEL:
              ONDE: aqui
              CÓDIGO:
                <Suspense fallback={<p>Loading...</p>}>
              RESULTADO:
                loading global por rota
              (não aplicado, apenas comentado) */}
        </main>

        <footer
          className="text-center p-4 flex items-center justify-center gap-4"
          // ALTERAÇÃO POSSÍVEL:
          // ONDE: nesta className
          // CÓDIGO:
          //   flex-col
          // RESULTADO:
          //   footer em coluna
          // (não aplicado, apenas comentado)
        >
          DIW {data.getFullYear()}
          {/* ALTERAÇÃO POSSÍVEL:
              ONDE: aqui
              CÓDIGO:
                ©
              RESULTADO:
                copyright explícito
              (não aplicado, apenas comentado) */}

          <Relogio />
          {/* ALTERAÇÃO POSSÍVEL:
              ONDE: neste componente
              CÓDIGO:
                remover Relogio
              RESULTADO:
                layout passa a Server Component puro
              (não aplicado, apenas comentado) */}
        </footer>

      </body>
    </html>
  );
}
